apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      resources:
        limits:
          cpu: 1000m
          memory: 1GB
        requests:
          cpu: 500m
          memory: 512Mi
      - image: registry.redhat.io/rhel8/postgresql-12:1-140
        env:
        - name: POSTGRESQL_USER
          value: postgres1
        - name: POSTGRESQL_PASSWORD
          value: postgres1
        - name: POSTGRESQL_DATABASE
          value: db
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/pgsql/data:Z
          name: db-data
      volumes:
      - name: db-data
        emptyDir: {} 
