apiVersion: v1
kind: Service
metadata:
  name: resultsvc
  namespace: example-voting
  labels:
    app: result
spec:
  type: ClusterIP
  ports:
    - port: 31001
      name: http-port
      protocol: TCP
      targetPort: 8080
  selector:
    app: result
