apiVersion: v1
kind: Service
metadata:
  name: votesvc
  namespace: example-voting
  labels:
    app: vote
spec:
  type: ClusterIP
  ports:
    - port: 31000
      name: http-port
      protocol: TCP
      targetPort: 5000
  selector:
    app: vote
